version: '3.9'

services:
  elastic-enrich-reference:
    image: node:gallium-alpine
    networks:
      hapi-fhir-postgres:
      hapi-fhir:
      kafka:
    environment:
      - ID_BATCH_SIZE=10
      - INPUT_FILE=input.dat
      - PGHOST=postgres-1
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=hapi
      - HAPI_PORT=8080
      - HAPI_URL=hapi-fhir
      - KAFKA_URL=kafka-01:9092,kafka-02:9092,kafka-03:9092
      - KAFKA_TOPIC=2xx
    deploy:
      resources:
        limits:
          memory: 2G
      restart_policy:
        condition: none
      placement:
        constraints:
          - "node.labels.name==node-1"
    command: sh -c "cd /app && npm run start && exit"
    volumes:
      - ../:/app

networks:
  hapi-fhir-postgres:
    name: hapi-fhir_postgres_public
    external: true
  hapi-fhir:
    name: hapi-fhir_public
    external: true
  kafka:
    name: kafka_public
    external: true
